### ISSUE TITLE
Plugin does not build due to changes in the Kaleidoscope API

### ISSUE THREAD

**Issue by noseglasses** [cdisselkoen/Kaleidoscope-Hardware-Virtual#2]
A class in the firmware core apparently has gained a new method

https://github.com/keyboardio/Arduino-HID/blob/c5b309cb600dcc195d936f263bd2187aa224b2df/src/HID.h#L95

Due to it missing in `class Keyboard_` 
https://github.com/cdisselkoen/Kaleidoscope-Hardware-Virtual/blob/5ec8384ab86ec9c84f4677cc151cf19ed3c9792b/src/VirtualHID/Keyboard.h#L24
the Hardware-Virtual plugin currently does not build with the latest version of the firmware.

**Comment by noseglasses** [comment]
There are also other problems due to a header `PluggableUSB.h` that is currently not added/replaced by the H-V plugin.

**Comment by cdisselkoen** [comment]
Indeed, that API change broke Hardware-Virtual.  I should really put a Watch on `KeyboardioHID` so that I can mirror any API changes there in Hardware-Virtual's `src/VirtualHID`.  I'll run off a quick patch that at least fixes the build problem.

Header `PluggableUSB.h` is only included from the AVR HID stack, which should not be included in any Hardware-Virtual build.  File `Kaleidoscope/src/kaleidoscope/hid.h` intentionally does not bring in any HID stack itself (it's effectively a unified API for either the AVR HID stack or our "virtual" HID stack); and file `Kaleidoscope/src/kaleidoscope/hid.cpp` is very careful to only select the `KeyboardioHID` library for non-virtual builds, using our `VirtualHID` library instead for virtual builds.  The upshot is that the `KeyboardioHID` library should not be included anywhere for virtual builds, and that library is the only place that references `PluggableUSB.h`.  Outside the core, all users should use the HID API defined in `Kaleidoscope/src/kaleidoscope/hid.h`, and only include that file (not any part of `KeyboardioHID.h`).

**Comment by cdisselkoen** [comment]
The build issue mentioned in the OP should be fixed now.

**Comment by noseglasses** [comment]
Thanks for reacting that quick. Also, thanks for the explanations. The problem with `PluggableUSB.h` is strange. I will see why my build fails.
